my $seq = "CCTGTAATCCCAGCTACCTGGGAGGCTGAGGCAGGAGAATCGCTTGAACTCGGGAGGCGGAAGTTGCAGTGAGCGGAGATCACGCCATTGTACTCCAGCCTGGGCAACAGAGCGAGACTCCTTCTGAAAGAAAAAACGAGATACAAATTC";
$seq =~ tr/atcgATCG/tagcTAGC/;
my $final = scalar reverse $seq;
print $final;